export const LOGIN = "LOGIN";
export const LOGIN_COMPLETE = "LOGIN_COMPLETE";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SET_USERNAME = "SET_USERNAME";
export const SET_USERNAME_ERROR = "SET_USERNAME_ERROR";

export const SET_TOKEN = "SET_TOKEN";
export const SET_TOKEN_COMPLETE = "SET_TOKEN_COMPLETE";
export const SET_TOKEN_ERROR = "SET_TOKEN_ERROR";

export const LOGOUT = "LOGOUT";

export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_COMPLETE = "GET_USER_INFO_COMPLETE";
export const GET_USER_INFO_ERROR = "GET_USER_INFO_ERROR";

export const EDIT_USER_INFO = "EDIT_USER_INFO";
export const EDIT_USER_INFO_COMPLETE = "EDIT_USER_INFO_COMPLETE";
export const EDIT_USER_INFO_ERROR = "EDIT_USER_INFO_ERROR";
